adding -64 flag to _run-sml script
git-svn-id: https://smlnj-gforge.cs.uchicago.edu/svn/smlnj@5791 d172b47e-f5d9-4df3-ab46-1c4da947e531

diff --git a/config/trunk/_run-sml b/config/trunk/_run-sml
--- a/config/trunk/_run-sml
+++ b/config/trunk/_run-sml
@@ -57,16 +57,6 @@ RUN_DIR=$BIN_DIR/.run
 # the path of the directory in which the heap images are kept.
 HEAP_DIR=$BIN_DIR/.heap
 
-#
-# the following could be replaced with some site specific code
-#
-ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys"`
-if [ "$?" != "0" ]; then
-  echo "$CMD: unable to determine architecture/operating system"
-  exit 1
-fi
-eval $ARCH_N_OPSYS
-
 #############################################################################
 #
 # END SITE SPECIFIC STUFF
@@ -90,6 +80,7 @@ if [ `basename "$0"` = sml ] ; then
 fi
 
 ALLOC=""
+SIZE_OPT="-32"
 
 #
 # Process command line arguments
@@ -97,6 +88,8 @@ ALLOC=""
 while [ "$#" != "0" ]; do
   arg=$1
   case "$arg" in
+    -32) shift; SIZE_OPT=$arg ;;
+    -64) shift; SIZE_OPT=$arg ;;
     @SMLrun=*)
       shift
       RUN=`echo $arg | sed 's/@SMLrun=//'`
@@ -131,6 +124,16 @@ while [ "$#" != "0" ]; do
       ;;
   esac
 done
+
+#
+# the following could be replaced with some site specific code
+#
+ARCH_N_OPSYS=`"$BIN_DIR/.arch-n-opsys" $SIZE_OPT`
+if [ "$?" != "0" ]; then
+  echo "$CMD: unable to determine architecture/operating system"
+  exit 1
+fi
+eval $ARCH_N_OPSYS
 
 #
 # Try to figure out the CPU's cache size and set the allocation area
