Some preliminary changes to support using a 64-bit compiler to   generate the bin files.  Unfortunately, this does not work yet   because of a issue (see bug #238).
git-svn-id: https://smlnj-gforge.cs.uchicago.edu/svn/smlnj@6041 d172b47e-f5d9-4df3-ab46-1c4da947e531

diff --git a/sml/trunk/system/cmb-cross b/sml/trunk/system/cmb-cross
--- a/sml/trunk/system/cmb-cross
+++ b/sml/trunk/system/cmb-cross
@@ -3,11 +3,22 @@
 # COPYRIGHT (c) 2019 The Fellowship of SML/NJ (http://www.smlnj.org)
 # All rights reserved.
 #
-# usage: cmb-cross [ -z ] <target>
-#	<target>	-- one of amd64-unix, ppc-unix, sparc-unix, x86-unix, or x86-win32
+# usage: cmb-cross [ -32 | -64 ] [ -z ] <TARGET>
+#	<TARGET>	-- one of amd64-unix, ppc-unix, sparc-unix, x86-unix, or x86-win32
 #
-# cross compile to the specified target
+# cross compile to the specified TARGET
 #
+
+usage() {
+  echo "usage: cmb-cross [ options ] <target>"
+  echo "  Options:"
+  echo "    -32 | -64     -- size option for compiler"
+  echo "    -z            -- archive result as gzipped tar file"
+  echo "    -C<ctl>=<v>   -- control argument passed to compile command"
+  echo "    <target>      -- one of amd64-unix, ppc-unix, sparc-unix,"
+  echo "                     x86-unix, or x86-win32"
+  exit 1
+}
 
 this=$0
 here=`pwd`
@@ -15,15 +26,35 @@ cd ../..
 twoup=`pwd`
 cd $here
 
-# compilation flags for final pass
-#
+SIZE_OPT=
 CTL_FLAGS=
+SIZE_OPT="-32"
+MAKE_TARBALL=no
+TARGET=
 
-usage() {
-  echo "usage: cmb-cross [ -z ] <target>"
-  echo "where <target> is one of amd64-unix, ppc-unix, sparc-unix, x86-unix, or x86-win32"
-  exit 1
-}
+#
+# Parse command line
+#
+while [ "$#" != 0 ] ; do
+    arg=$1; shift
+    case $arg in
+    -32) SIZE_OPT="-32" ;;
+    -64) SIZE_OPT="-64" ;;
+    -z) MAKE_TARBALL=yes ;;
+    -C) CTL_FLAGS="$CTL_FLAGS $arg" ;;
+    amd64-unix|ppc-unix|sparc-unix|x86-unix|x86-win32)
+	TARGET=$arg
+	;;
+    *)
+	echo "$this: unknown argument \"$arg\""
+	usage
+	;;
+    esac
+done
+
+if [ x"$TARGET" = x ] ; then
+  usage
+fi
 
 to_lower() {
   echo $@ | tr "[:upper:]" "[:lower:]"
@@ -32,18 +63,6 @@ to_lower() {
 to_upper() {
   echo $@ | tr "[:lower:]" "[:upper:]"
 }
-
-# check for "-z" flag
-if [ x"$1" = "x-z" ] ; then
-  shift
-  build_tarball=yes
-else
-  build_tarball=no
-fi
-
-if [ $# -ne 1 ] ; then
-  usage
-fi
 
 # check linking command
 LINK=$twoup/bin/.link-sml
@@ -66,9 +85,9 @@ fi
 HOST_ARCH=$(to_upper $ARCH)
 HOST_OPSYS=$(to_upper $OPSYS)
 
-# determine the target ARCH, OPSYS, SIZE, and ENDIANESS variables
-target=$1
-case $target in
+# determine the TARGET ARCH, OPSYS, SIZE, and ENDIANESS variables
+#
+case $TARGET in
   amd64-unix)
     architecture=amd64
     TARGET_ARCH=AMD64;
@@ -104,7 +123,7 @@ case $target in
     TARGET_SIZE=32
     TARGET_ENDIANESS=LITTLE
     ;;
-  *) echo "cmb-cross: unrecognized target '$target'"
+  *) echo "cmb-cross: unrecognized TARGET '$TARGET'"
      exit 1
   ;;
 esac
@@ -114,30 +133,30 @@ architecture=$(to_lower $TARGET_ARCH)
 
 unset VERSIONTOOL_BUMP_RELEASE
 
-echo "$this: build $target-cross bin/boot files"
-../../bin/sml -DNO_PLUGINS \$smlnj/cmb.cm << XXXX
+echo "$this: build $TARGET-cross bin/boot files"
+../../bin/sml $SIZE_OPT -DNO_PLUGINS \$smlnj/cmb.cm << XXXX
 #set (CMB.symval "ARCH_${HOST_ARCH}") NONE;
 #set (CMB.symval "OPSYS_${HOST_OPSYS}") NONE;
 #set (CMB.symval "ARCH_${TARGET_ARCH}") (SOME 1);
 #set (CMB.symval "OPSYS_${TARGET_OPSYS}") (SOME 1);
 #set (CMB.symval "TARGET_SIZE_${TARGET_SIZE}") (SOME 1);
 #set (CMB.symval "TARGET_${TARGET_ENDIANESS}_ENDIAN") (SOME 1);
-CMB.make' (SOME "$target-cross");
+CMB.make' (SOME "$TARGET-cross");
 XXXX
 
 # the following is equivalent to running
 #
-#	./makeml -boot $target-cross.boot.x86-unix -rebuild $architecture
+#	./makeml -boot $TARGET-cross.boot.x86-unix -rebuild $architecture
 #
-echo "$this: cross compile to $target"
+echo "$this: cross compile to $TARGET"
 
 if [ $HOST_OPSYS = win32 ] ; then
     SUFFIX=$(to_lower "${HOST_ARCH}-win32")
 else
     SUFFIX=$(to_lower "${HOST_ARCH}-unix")
 fi
-CROSS_BIN_DIR="${target}-cross.bin.${SUFFIX}"
-CROSS_BOOT_DIR="${target}-cross.boot.${SUFFIX}"
+CROSS_BIN_DIR="${TARGET}-cross.bin.${SUFFIX}"
+CROSS_BOOT_DIR="${TARGET}-cross.boot.${SUFFIX}"
 
 MODE="@SMLrebuild=${architecture}"
 
@@ -146,21 +165,21 @@ export CM_PATHCONFIG
 
 cd $CROSS_BOOT_DIR
 
-echo $this: $LINK $RUN @SMLboot=BOOTLIST @SMLheap=sml $MODE $CTL_FLAGS
-if $LINK $RUN @SMLboot=BOOTLIST @SMLheap=sml $MODE $CTL_FLAGS ; then
+echo $this: $LINK $SIZE_OPT @SMLboot=BOOTLIST @SMLheap=sml $MODE $CTL_FLAGS
+if $LINK $SIZE_OPT @SMLboot=BOOTLIST @SMLheap=sml $MODE $CTL_FLAGS ; then
     # back to the system directory
     #
     cd $here
-    # the new boot/bin files will be in "${architecture}.boot.${target}"
-    # and "${architecture}.bin.${target}"; we rename them with the
+    # the new boot/bin files will be in "${architecture}.boot.${TARGET}"
+    # and "${architecture}.bin.${TARGET}"; we rename them with the
     # standard naming convention by replacing "${architecture}" with "sml"
     #
     for xxx in bin boot ; do
-	if [ -d "${architecture}.${xxx}.${target}" ] ; then
-            rm -rf "sml.${xxx}.${target}"
-	    mv "${architecture}.${xxx}.${target}" "sml.${xxx}.${target}"
+	if [ -d "${architecture}.${xxx}.${TARGET}" ] ; then
+            rm -rf "sml.${xxx}.${TARGET}"
+	    mv "${architecture}.${xxx}.${TARGET}" "sml.${xxx}.${TARGET}"
 	else
-	    echo "$this: ${architecture}.${xxx}.${target} is missing!"
+	    echo "$this: ${architecture}.${xxx}.${TARGET} is missing!"
 	    exit 1
 	fi
     done
@@ -173,6 +192,6 @@ else
     exit 1
 fi
 
-if [ $build_tarball = "yes" ] ; then
-  tar -cf - sml.boot.${target} | gzip > boot.$target.tgz
+if [ $MAKE_TARBALL = "yes" ] ; then
+  tar -cf - sml.boot.${TARGET} | gzip > boot.$TARGET.tgz
 fi
